### ISSUE TITLE
plantuml render cannot work

### ISSUE THREAD

**Issue by RyukerLiu** [HillLiu/docker-mdbook#2]
plantuml render cannot work

**Comment by HillLiu** [comment]
@RyukerLiu  Check the sample page first.
http://localhost:3000/chapter_3.html

src
https://github.com/HillLiu/docker-mdbook/blob/master/mdbook-demo/src/chapter_3.md

or you could get any debug formation from following command.

```
./preview.sh logs
```

**Comment by Edgehere** [comment]
Hi I just wanted to ask is there a way to update the uml diagrams, I find that diagrams like say:

```
@startuml
class Class
object Object
@enduml
```
do work however diagrams with possible new components like: 
```
@startuml
class Class
object Object
json JSON {
   "fruit":"Apple",
   "size":"Large",
   "color": ["Red", "Green"]
}
@enduml
```
don't really work. I was just comparing them to all the possibilities from https://plantuml.com/ . Although some of the new ones might be Non-uml. Just wanted to ask if there was a way to incorporate it either way.

**Comment by HillLiu** [comment]
@Edgehere  could u open a new issue for it?


> Hi I just wanted to ask is there a way to update the uml diagrams, I find that diagrams like say:
> 
> ```
> @startuml
> class Class
> object Object
> @enduml
> ```
> 
> do work however diagrams with possible new components like:
> 
> ```
> @startuml
> class Class
> object Object
> json JSON {
>    "fruit":"Apple",
>    "size":"Large",
>    "color": ["Red", "Green"]
> }
> @enduml
> ```
> 
> don't really work. I was just comparing them to all the possibilities from https://plantuml.com/ . Although some of the new ones might be Non-uml. Just wanted to ask if there was a way to incorporate it either way.
