### ISSUE TITLE
Error running mdbook Docker 

### ISSUE THREAD

**Issue by Edgehere** [HillLiu/docker-mdbook#4]
Hi I have an issue when I try to run your code. I have pulled the image from docker hub and I have created a test directory with copied and pasted `SUMMARY.md` file. I have also placed the `preview.sh` file from the github rep. I get the following error when I run the command `./preview.sh start`. 

Error Code: 

```
Error response from daemon: No such container: mdbook
Error: No such container: mdbook
docker run -d -p 3000:3000 -p 3001:3001 -v /var/run/docker.sock:/var/run/docker.sock -v /Users/samiselcuk/Desktop/project docs/test:/mdbook/src --name mdbook hillliu/mdbook serve -n 0.0.0.0 -w 3001
docker: invalid reference format.
See 'docker run --help'.
Error: No such container: mdbook
```

How would I be able to fix this issue?

Directory:

```
.
├── SUMMARY.md
└── preview.sh
```

**Comment by HillLiu** [comment]
@Edgehere I didn't find issue from my part. could u try following command directly.
```
docker run --rm  hillliu/mdbook -V
```
and it should output `mdbook v0.3.1`

If still no lucky for u, you could try remove the image and run above command again.
```
docker rmi hillliu/mdbook
```

**Comment by Edgehere** [comment]
Hi thanks for the response I have ran the command `docker run --rm hillliu/mdbook -V` and it does output `mdbook v0.3.1`, after that I tried the command `./preview.sh start`.  I have also tried removing and reinstalling the image and running the `docker run --rm hillliu/mdbook -V ` command again. Tried both of your recommended suggestions but they do not work and I get the same error message above.

**Comment by HillLiu** [comment]
@Edgehere 
I rewrite the preview.sh, it should be fixed the issue.
https://github.com/HillLiu/docker-mdbook/commit/e11d813523d11d8a8b12512848ad1a6ed987edc6

I guess there are two issues from your environment.
1. Your docker.sock not local at /var/run/docker.sock
2. When do stop the container not exists.

BTW, you could just renew the preview.sh, it should work.

**Comment by HillLiu** [comment]
@Edgehere Apologizes for you do many times try.

Avoid you feel tired, the `docker: invalid reference format` mostly mean the pwd not assign value correct. 

In your command is "docs/test:/mdbook/src",
So you could hard code it with `MDBOOK_SRC`
The command will look like
```
MDBOOK_SRC=./docs/test ./preview.sh start
```

if u still happy help with me trial and error, I make a little change for preview.sh, you could try again.

**Comment by Edgehere** [comment]
Hi this seems lie a recurring theme now but I have updated the `preview.sh` and then ran the command `MDBOOK_SRC=./docs/test ./preview.sh start` it gave me a new error: 

```
docker run -p 3000:3000 -p 3001:3001 -v ./docs/test:/mdbook/src --name mdbook --rm -d hillliu/mdbook serve -n 0.0.0.0 -w 3001
docker: Error response from daemon: create ./docs/test: "./docs/test" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
Error: No such container: mdbook
```
I am using a Macbook you think the issue is because of the changes in OS right?

**Comment by HillLiu** [comment]
I forgot the 'host-src' should be an absolute path.
https://docs.docker.com/engine/reference/run/#volume-shared-filesystems

So you could change it to something like
```
MDBOOK_SRC=/your-root/docs/test ./preview.sh start
```

In this folder (/your-root/docs/test), you should contain SUMMARY.md and preview.sh.

And SUMMARY.md should follow 
```
# Summary

- [Chapter 1](./chapter_1.md)
```

**Comment by Edgehere** [comment]
Thank you I finally got it to work. Thanks for everything :)

**Comment by Edgehere** [comment]
Hi the previous issue was on MacOS and now I wanted to create the same mdbook setup for windows 10. The setup does not work and I get the error below. I tried both of the methods ` ./preview.sh start` and `MDBOOK_SRC=/your-root/docs/test ./preview.sh start`. Both of the methods create an error. 

```
MDBOOK_SRC=C:/Users/Edge/Desktop/coding/project-docs/Tester/docs/test ./preview.sh start
docker run -p 3000:3000 -p 3001:3001 -v C:/Users/Edge/Desktop/coding/project-docs/Tester/docs/test:/mdbook/src --name mdbook --rm -d hillliu/mdbook 
serve -n 0.0.0.0 -w 3001
d1d65c5ce94ff74eecc91676c8fd0172ddc2ada777b8eb0d2c5f925e0534146e
bash: line 1: http://localhost:3000: No such file or directory
Error: No such container: mdbook
```

**Comment by HillLiu** [comment]
@Edgehere  There are several things you could do.

1. you need make sure your windows env could run linux container image.
Actually the linux container with widows container is very different.
if u want run linux container in windows, you need do something such as:

```
window -> virtualize to linux -> run docker -> run linux container image
```
if u need help, you could check this article 
https://hackernoon.com/how-to-run-docker-linux-containers-natively-on-windows-ti1i3uxr
I didn't have a Windows env to try this so maybe u need other Windows expert to help u.
but you could through run simple alpine image to make sure your window env could run linux container.

```
docker run --rm alpine cat /etc/alpine-release

# it should dump "3.16.2"
```

2. After u confirm you could run linux container in windows, you could try get more debug message by remove the "-d" parameter.
I already upgrade mdbook version for new plantuml syntax, so the command will have a little different.

```
docker run -p 3000:3000 -p 3001:3001 -v C:/Users/Edge/Desktop/coding/project-docs/Tester/docs/test:/mdbook/src --name mdbook --rm hillliu/mdbook 
serve -n 0.0.0.0
```

3. if It show more debug message, u could share again.



> Hi the previous issue was on MacOS and now I wanted to create the same mdbook setup for windows 10. The setup does not work and I get the error below. I tried both of the methods ` ./preview.sh start` and `MDBOOK_SRC=/your-root/docs/test ./preview.sh start`. Both of the methods create an error.

**Comment by Edgehere** [comment]
Hi thanks for the help I have installed Ubuntu and followed all the steps for the shared article. Also I can run `docker run --rm alpine cat /etc/alpine-release` perfectly fine. when I try the command above it gives this error msg: 
```
~$ docker run -p 3000:3000 -p 3001:3001 -v C:/Users/Edge/Desktop/python-projects/mac/project-docs/Tester/docs/test:/mdbook/src --name mdbook --rm hillliu/mdbook serve -n 0.0.0.0
docker: Error response from daemon: invalid mode: /mdbook/src.
See 'docker run --help'
```

**Comment by Edgehere** [comment]
Finally I figured it out. Sorry for all the troubles, and thanks for everything.

**Comment by Edgehere** [comment]
Hi so I made it work but I think there's a problem with the changes you made. When I update the any markdown file mdbook does not listen to changes and doesnt auto update the local host website. So for example I edit chap1.md and there are no outputs in the container.

```
docker run -p 3888:3000 -v /mnt/c/Users/Edge/Desktop/python-projects/mac/project-docs/Tester/docs/test:/mdbook/src --name mdbook --rm -d hillliu/mdbook serve -n 0.0.0.0
fd3933c943a8d0f845e789d917bd5179820990377333d4219b759fb7324bc33d
http://localhost:3888
2022-09-05 17:24:34 [INFO] (mdbook::book): Book building has started
2022-09-05 17:24:34 [INFO] (mdbook::book): Running the html backend
2022-09-05 17:24:34 [INFO] (mdbook::cmd::serve): Serving on: http://0.0.0.0:3000
2022-09-05 17:24:34 [INFO] (warp::server): Server::run; addr=0.0.0.0:3000
2022-09-05 17:24:34 [INFO] (warp::server): listening on http://0.0.0.0:3000
2022-09-05 17:24:34 [INFO] (mdbook::cmd::watch): Listening for changes...
```

**Comment by HillLiu** [comment]
@Edgehere 

About `docker: Error response from daemon: invalid mode`, you could check stackoverflow,
https://stackoverflow.com/a/53097168/18675835
the path may change to 
```
//c/Users/Edge/Desktop/python-projects/mac/project-docs/Tester/docs/test://mdbook/src
```

---


I see a record mention the file changed. 

Do you mean that when u run docker the file not change, but you run command directly the file will change? 
```
2022-09-05 14:26:05 [INFO] (mdbook::cmd::serve): Files changed: ["C:\\Users\\Edge\\Desktop\\python-projects\\mac\\project-docs\\Tester\\mdbook-test2\\src\\chapter_1.md"]
```

Do you check it with linux or macos version, I guess the problem it also related windows system.
The windows file system often use NTFS, it's monitor mechanism is very different with linux base one,
I think docker may could not handle it well.
I guess the best way should use such as vmware to simulate linux os and linux file system (such as ext4).
This combination should have less problem.

**Comment by Edgehere** [comment]
yes sorry for the reply, yes I believe the problem might be related to windows. Thanks for trying to help though.
