### ISSUE TITLE
Some plantuml diagrams not working 

### ISSUE THREAD

**Issue by Edgehere** [HillLiu/docker-mdbook#5]
Hi I just wanted to ask is there a way to update the uml diagrams, I find that diagrams like say:

```
@startuml
class Class
object Object
@enduml
```
do work however diagrams with possible new components like:

```
@startuml
class Class
object Object
json JSON {
   "fruit":"Apple",
   "size":"Large",
   "color": ["Red", "Green"]
}
@enduml
```
don't really work. I was just comparing them to all the possibilities from https://plantuml.com/ . Although some of the new ones might be Non-uml. Just wanted to ask if there was a way to incorporate it either way.

**Comment by HillLiu** [comment]
@Edgehere 
I already upgrade packages, please follow these updates.

1. you pull new image.
```
docker pull hillliu/mdbook
```

2. update preview.sh, git branch from "master" to "main"

3. After upgrade both of them, then you could run json format as

````
```plantuml
@startjson
{
   "fruit":"Apple",
   "size":"Large",
   "color": ["Red", "Green"]
}
@endjson
```
````
